In [88]:
import selenium
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException,ElementNotInteractableException
from selenium.webdriver.common.action_chains import ActionChains
import warnings
warnings.filterwarnings('ignore')
import time

## 1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:
## A) Rank
## B) Name
## C) Artist
## D) Upload date
## E) Views

In [141]:
driver = webdriver.Chrome()
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [142]:
Rank=[]
Name=[]
Artist=[]
Date=[]
View=[]

In [143]:
try:
    for i in range(1,31):
        rank = driver.find_element(By.XPATH,'/html/body/div[2]/div/div[3]/main/div[3]/div[3]/div[1]/table[2]/tbody/tr[{}]/td[1]'.format(i))
        Rank.append(rank.text)
        title=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[3]/main/div[3]/div[3]/div[1]/table[2]/tbody/tr[{}]/td[2]'.format(i))
        Name.append(title.text)
        artist=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[3]/main/div[3]/div[3]/div[1]/table[2]/tbody/tr[{}]/td[3]'.format(i))
        Artist.append(artist.text)
        date=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[3]/main/div[3]/div[3]/div[1]/table[2]/tbody/tr[{}]/td[5]'.format(i))
        Date.append(date.text)
        view=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[3]/main/div[3]/div[3]/div[1]/table[2]/tbody/tr[{}]/td[4]'.format(i))
        View.append(view.text)
except NoSuchElementException as e:
    pass

In [144]:
ds1=pd.DataFrame({'Rank':Rank,'Title':Name,'Artist':Artist,'Published date':Date,'Views':View})
ds1

,Rank,Title,Artist,Published date,Views
0,1.,"""Baby Shark Dance""[6]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",13.36
1,2.,"""Despacito""[9]",Luis Fonsi,"January 12, 2017",8.26
2,3.,"""Johny Johny Yes Papa""[16]",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.80
3,4.,"""Bath Song""[17]",Cocomelon - Nursery Rhymes,"May 2, 2018",6.41
4,5.,"""Shape of You""[18]",Ed Sheeran,"January 30, 2017",6.08
5,6.,"""See You Again""[21]",Wiz Khalifa,"April 6, 2015",6.03
6,7.,"""Wheels on the Bus""[26]",Cocomelon - Nursery Rhymes,"May 24, 2018",5.56
7,8.,"""Phonics Song with Two Words""[27]",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.48
8,9.,"""Uptown Funk""[28]",Mark Ronson,"November 19, 2014",5.03
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[29]",Miroshka TV,"February 27, 2018",4.97
10,11.,"""Gangnam Style""[30]",officialpsy,"July 15, 2012",4.90
11,12.,"""Masha and the Bear – Recipe for Disaster""[35]",Get Movies,"January 31, 2012",4.56
12,13.,"""Dame Tu Cosita""[36]",Ultra Records,"April 5, 2018",4.44
13,14.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",4.06
14,15.,"""Sugar""[38]",Maroon 5,"January 14, 2015",3.93
15,16.,"""Counting Stars""[39]",OneRepublic,"May 31, 2013",3.87
16,17.,"""Roar""[40]",Katy Perry,"September 5, 2013",3.87
17,18.,"""Baa Baa Black Sheep""[41]",Cocomelon - Nursery Rhymes,"June 25, 2018",3.78
18,19.,"""Waka Waka (This Time for Africa)""[42]",Shakira,"June 4, 2010",3.73
19,20.,"""Sorry""[43]",Justin Bieber,"October 22, 2015",3.71
20,21.,"""Lakdi Ki Kathi""[44]",Jingle Toons,"June 14, 2018",3.69
21,22.,"""Thinking Out Loud""[45]",Ed Sheeran,"October 7, 2014",3.66
22,23.,"""Dark Horse""[46]",Katy Perry,"February 20, 2014",3.59
23,24.,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.55
24,25.,"""Perfect""[48]",Ed Sheeran,"November 9, 2017",3.54
25,26.,"""Faded""[49]",Alan Walker,"December 3, 2015",3.51
26,27.,"""Let Her Go""[50]",Passenger,"July 25, 2012",3.51
27,28.,"""Girls Like You""[51]",Maroon 5,"May 31, 2018",3.48
28,29.,"""Lean On""[52]",Major Lazer Official,"March 22, 2015",3.46
29,30.,"""Bailando""[53]",Enrique Iglesias,"April 11, 2014",3.45

In [145]:
driver.quit()

## 2. Scrape the details team India’s international fixtures from bcci.tv.
## Url = https://www.bcci.tv/.
## You need to find following details:
## A) Match title (I.e. 1 ODI)
## B) Series
## C) Place
## D) Date
## E) Time
## Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [156]:
driver = webdriver.Chrome()
driver.get('http://www.bcci.tv/')
inter=driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
inter.click()

In [152]:
for j in range(0,10):
    try:
        element = driver.find_element(By.XPATH,'//*[@id="fixtures"]/div[3]/div[2]/div/button')
        driver.execute_script("arguments[0].click();", element)
    except NoSuchElementException as e:
        break

In [153]:
match=[]
Series=[]
Place=[]
Date=[]
Time=[]
Team1=[]
Team2=[]

In [154]:
mat=driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[3]/div/span[1]')
for i in mat:
    match.append(i.text)
TeamL=driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[2]/div[1]/div[1]')
for i in TeamL:
    Team1.append(i.text)
TeamR=driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[2]/div[1]/div[3]')
for i in TeamR:
    Team2.append(i.text)
grd=driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[3]/div/span[2]')
for i in grd:
    Place.append(i.text)
date=driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[1]/div/div[1]')
for i in date:
    Date.append(i.text)
time=driver.find_elements(By.XPATH,'//*[@id="match-card"]/div[1]/div/div[2]')
for i in time:
    Time.append(i.text)

In [155]:
df=pd.DataFrame({'Team1':Team1,'Team2':Team2})
ds2=pd.DataFrame({'Match Title':match,'Series':df['Team1']+' vs '+df['Team2'],'Place':Place,'Date':Date,'Time':Time})
ds2

,Match Title,Series,Place,Date,Time
0,Quarter Final 1 -,India Women vs Malaysia Women,"Pingfeng Cricket Field,",21 SEP 2023,6:30 AM IST
1,1st ODI -,India vs Australia,"Punjab Cricket Association IS Bindra Stadium,",22 SEP 2023,1:30 PM IST
2,2nd ODI -,India vs Australia,"Holkar Cricket Stadium,",24 SEP 2023,1:30 PM IST
3,3rd ODI -,India vs Australia,"Saurashtra Cricket Association Stadium,",27 SEP 2023,1:30 PM IST
4,1st ODI -,India vs England,"Barsapara Cricket Stadium,",30 SEP 2023,2:00 PM IST
5,1st T20I -,India vs TBD,"Pingfeng Cricket Field,",3 OCT 2023,6:30 AM IST
6,2nd ODI -,India vs Netherlands,"Greenfield International Stadium,",3 OCT 2023,2:00 PM IST
7,1st ODI -,India vs Australia,"MA Chidambaram Stadium,",8 OCT 2023,2:00 PM IST
8,2nd ODI -,India vs Afghanistan,"Arun Jaitley Stadium,",11 OCT 2023,2:00 PM IST
9,3rd ODI -,India vs Pakistan,"Narendra Modi Stadium,",14 OCT 2023,2:00 PM IST
10,4th ODI -,India vs Bangladesh,"Maharashtra Cricket Association Stadium,",19 OCT 2023,2:00 PM IST
11,5th ODI -,India vs New Zealand,"Himachal Pradesh Cricket Association Stadium,",22 OCT 2023,2:00 PM IST
12,6th ODI -,India vs England,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,29 OCT 2023,2:00 PM IST
13,7th ODI -,India vs Sri Lanka,"Wankhede Stadium,",2 NOV 2023,2:00 PM IST
14,8th ODI -,India vs South Africa,"Eden Gardens,",5 NOV 2023,2:00 PM IST
15,9th ODI -,India vs Netherlands,"M Chinnaswamy Stadium,",12 NOV 2023,2:00 PM IST
16,1st T20I -,India vs Australia,"Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,",23 NOV 2023,7:00 PM IST
17,2nd T20I -,India vs Australia,"Greenfield International Stadium,",26 NOV 2023,7:00 PM IST
18,3rd T20I -,India vs Australia,"Barsapara Cricket Stadium,",28 NOV 2023,7:00 PM IST
19,4th T20I -,India vs Australia,"Vidarbha Cricket Association Stadium,",1 DEC 2023,7:00 PM IST
20,5th T20I -,India vs Australia,"Rajiv Gandhi International Stadium,",3 DEC 2023,7:00 PM IST
21,1st T20I -,South Africa vs India,"Kingsmead,",10 DEC 2023,9:30 PM IST
22,2nd T20I -,South Africa vs India,"St George's Park,",12 DEC 2023,9:30 PM IST
23,3rd T20I -,South Africa vs India,"The Wanderers Stadium,",14 DEC 2023,9:30 PM IST
24,1st ODI -,South Africa vs India,Johannesburg,17 DEC 2023,2:00 PM IST
25,2nd ODI -,South Africa vs India,"St George's Park,",19 DEC 2023,2:00 PM IST
26,3rd ODI -,South Africa vs India,"Boland Park,",21 DEC 2023,2:00 PM IST
27,1st Test -,South Africa vs India,"SuperSport Park,",26 DEC 2023,1:30 PM IST
28,2nd Test -,South Africa vs India,"Newlands,",3 JAN 2024,1:30 PM IST
29,1st T20I -,India vs Afghanistan,"Punjab Cricket Association IS Bindra Stadium,",11 JAN 2024,7:00 PM IST
30,2nd T20I -,India vs Afghanistan,"Holkar Cricket Stadium,",14 JAN 2024,7:00 PM IST
31,3rd T20I -,India vs Afghanistan,"M Chinnaswamy Stadium,",17 JAN 2024,7:00 PM IST
32,1st Test -,India vs England,"Rajiv Gandhi International Stadium,",25 JAN 2024,9:30 AM IST
33,2nd Test -,India vs England,"Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,",2 FEB 2024,9:30 AM IST
34,3rd Test -,India vs England,"Saurashtra Cricket Association Stadium,",15 FEB 2024,9:30 AM IST
35,4th Test -,India vs England,"JSCA International Stadium Complex,",23 FEB 2024,9:30 AM IST
36,5th Test -,India vs England,"Himachal Pradesh Cricket Association Stadium,",7 MAR 2024,9:30 AM IST

In [157]:
driver.quit()

## 3. Scrape the details of State-wise GDP of India from statisticstime.com.
## Url = http://statisticstimes.com/
## You have to find following details: 
## A)Rank
## B) State
## C) GSDP(18-19)- at current prices
## D) GSDP(19-20)- at current prices
## E) Share(18-19)
## F) GDP( billion)
## Note: - From statisticstimes home page you have to reach to economy page through code.

In [168]:
driver = webdriver.Chrome()
driver.get('http://statisticstimes.com/')

In [159]:
eco=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
action_chains = ActionChains(driver)
action_chains.move_to_element(eco).perform()

In [160]:
gdp=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
link=gdp.get_attribute('href')
driver.get(link)

In [161]:
gdpi=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
link=gdpi.get_attribute('href')
driver.get(link)

In [162]:
Rank=[]
Name=[]
GSDP18=[]
GSDP19=[]
Share=[]
GDP=[]

In [163]:
for i in range(1,34):
    rank=driver.find_element(By.XPATH,'/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[1]'.format(i))
    Rank.append(rank.text)
    name=driver.find_element(By.XPATH,'/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[2]'.format(i))
    Name.append(name.text)
    gsdp18=driver.find_element(By.XPATH,'/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[4]'.format(i))
    GSDP18.append(gsdp18.text)
    gsdp19=driver.find_element(By.XPATH,'/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[3]'.format(i))
    GSDP19.append(gsdp19.text)
    share=driver.find_element(By.XPATH,'/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[5]'.format(i))
    Share.append(share.text)
    gdp=driver.find_element(By.XPATH,'/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[6]'.format(i))
    GDP.append(gdp.text)

In [164]:
ds3=pd.DataFrame({'Rank ':Rank,'State':Name,'GSDP(18-19)- at current prices':GSDP18,'GSDP(19-20)- at current prices':GSDP19,'Share(18-19) ':Share,'GDP($ billion) ':GDP})
ds3

,Rank,State,GSDP(18-19)- at current prices,GSDP(19-20)- at current prices,Share(18-19),GDP($ billion)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [169]:
driver.quit()

## 4. Scrape the details of trending repositories on Github.com.
## Url = https://github.com/
## You have to find the following details:
## A) Repository title
## B) Repository description
## C) Contributors count
## D) Language used

In [182]:
driver = webdriver.Chrome()
driver.get('https://github.com/')

In [183]:
signin=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/div/div/a')
driver.execute_script("arguments[0].click();", signin)

In [184]:
print('Enter the mail id:')
username = input()
print('Enter the password:')
password = input()
Username = driver.find_element(By.XPATH,'//input[@id="login_field"]')
Username.send_keys(username)
Password = driver.find_element(By.CSS_SELECTOR,'#password')
Password.send_keys(password)
submit=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/main/div/div[4]/form/div/input[13]')
driver.execute_script("arguments[0].click();", submit)

Enter the mail id:
gomathikokila2409@gmail.com
Enter the password:
Kokila@2409

In [185]:
try:
    menu=driver.find_element(By.XPATH,'//*[@id="dialog-show-dialog-227b30f5-1c51-41db-afb9-c2c5a21085d8"]')
    driver.execute_script("arguments[0].click();", menu)
except NoSuchElementException as e:
    menu=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/deferred-side-panel/include-fragment/button')
    driver.execute_script("arguments[0].click();", menu)

In [186]:
try:
    exp=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/deferred-side-panel/div/modal-dialog/div[3]/nav/nav-list/ul/li[1]/a/span[2]')
    driver.execute_script("arguments[0].click();", exp)
except NoSuchElementException as e:
    exp=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[1]/deferred-side-panel/div/modal-dialog/div[3]/nav/nav-list/ul/li[1]/a/span[2]')
    driver.execute_script("arguments[0].click();", exp)

In [187]:
try:
    trend=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/main/div[1]/nav/div/a[3]')
    driver.execute_script("arguments[0].click();", trend)
except NoSuchElementException as e:
    trend=driver.find_element(By.XPATH,'/html/body/div[1]/div[6]/main/div[1]/nav/div/a[3]')
    driver.execute_script("arguments[0].click();", trend)

In [188]:
describ=[]
rep_title=[]
cont_count=[]
lang=[]

In [189]:
title=driver.find_elements(By.XPATH,'//a[@class="Link"]')
for i in title:
    rep_title.append(i.text)
rep_title.pop(0)
des=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
for i in des:
    describ.append(i.text)
span_element = driver.find_elements(By.XPATH,'//span[@class="d-inline-block mr-3"]')
for i in span_element:
    class_name_to_count = "d-inline-block"
    elements_with_class = i.find_elements(By.CLASS_NAME,class_name_to_count)
    cont_count.append(len(elements_with_class))
lan=driver.find_elements(By.XPATH,'//span[@itemprop="programmingLanguage"]')
for i in lan:
    lang.append(i.text)

In [95]:
ds4=pd.DataFrame({'Repository Title':rep_title,'Description':describ,'Contributer count':cont_count,'Language':lang})
ds4

,Repository Title,Description,Contributer count,Language
0,godotengine / godot,Godot Engine – Multi-platform 2D and 3D game e...,5,C++
1,coqui-ai / TTS,🐸💬 - a deep learning toolkit for Text-to-Speec...,5,Python
2,isocpp / CppCoreGuidelines,The C++ Core Guidelines are a set of tried-and...,5,Python
3,MonoGame / MonoGame,One framework for creating powerful cross-plat...,5,C#
4,aiwaves-cn / agents,An Open-source Framework for Autonomous Langua...,5,Python
5,zhile-io / pandora,"潘多拉，一个让你呼吸顺畅的ChatGPT。Pandora, a ChatGPT client...",4,Python
6,badlogic / heissepreise,Jo eh.,5,JavaScript
7,lodash / lodash,A modern JavaScript utility library delivering...,5,JavaScript
8,Klipper3d / klipper,Klipper is a 3d-printer firmware,5,C
9,stride3d / stride,Stride Game Engine (formerly Xenko),5,C#
10,nuejs / nuejs,Build user interfaces with 10x less code. Alte...,5,JavaScript
11,langchain-ai / langchain-nextjs-template,LangChain + Next.js starter template,1,TypeScript
12,commaai / openpilot,openpilot is an open source driver assistance ...,5,Python
13,facebookresearch / nougat,Implementation of Nougat Neural Optical Unders...,5,Python
14,KenneyNL / Starter-Kit-3D-Platformer,Godot,3,GDScript
15,godotengine / godot-docs,Godot Engine official documentation,5,reStructuredText
16,AUTOMATIC1111 / stable-diffusion-webui,Stable Diffusion web UI,5,Python
17,yoheinakajima / instagraph,Converts text input or URL into knowledge grap...,5,Python
18,godotengine / godot-demo-projects,Demonstration and Template Projects,5,GDScript
19,guidance-ai / guidance,A guidance language for controlling large lang...,5,Jupyter Notebook
20,FlaxEngine / FlaxEngine,Flax Engine – multi-platform 3D game engine,5,C++
21,ripienaar / free-for-dev,"A list of SaaS, PaaS and IaaS offerings that h...",5,HTML
22,fishaudio / Bert-VITS2,vits2 backbone with bert,5,Python
23,TheAlgorithms / Python,All Algorithms implemented in Python,5,Python
24,89luca89 / distrobox,Use any linux distribution inside your termina...,5,Shell

In [192]:
driver.quit()

## 5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/
## You have to find the following details:
## A) Song name
## B) Artist name
## C) Last week rank
## D) Peak rank
## E) Weeks on board

In [231]:
driver = webdriver.Chrome()
driver.get('https://www.billboard.com/')

In [232]:
menu=driver.find_element(By.XPATH,'//*[@id="main-wrapper"]/header/div/div[4]/div/div[1]/div[1]/button')
driver.execute_script("arguments[0].click();", menu)
plus=driver.find_element(By.XPATH,'//*[@id="mega-menu-item-charts"]/button')
driver.execute_script("arguments[0].click();", plus)
top=driver.find_element(By.XPATH,'//*[@id="main-wrapper"]/div[9]/div/div/div/ul/li[1]/ul/li[2]/a')
driver.execute_script("arguments[0].click();", top)

In [233]:
song=[]
artist=[]
rank=[]
peak_rank=[]
WOB=[]

In [234]:
for i in range(2,120):
    try: 
        songs=driver.find_element(By.XPATH,'/html/body/div[4]/main/div[2]/div[3]/div/div/div/div[2]/div[{}]/ul/li[4]/ul/li[1]/h3'.format(i))
        song.append(songs.text)
    except NoSuchElementException as e:
        continue
    try:
        artists=driver.find_element(By.XPATH,'/html/body/div[4]/main/div[2]/div[3]/div/div/div/div[2]/div[{}]/ul/li[4]/ul/li[1]/span'.format(i))
        artist.append(artists.text)
    except NoSuchElementException as e:
        continue
    try:
        ranks=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[3]/div/div/div/div[2]/div[{}]/ul/li[4]/ul/li[4]/span'.format(i))
        rank.append(ranks.text)
    except NoSuchElementException as e:
        continue
    try:
        p_rank=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[3]/div/div/div/div[2]/div[{}]/ul/li[4]/ul/li[5]/span'.format(i))
        peak_rank.append(p_rank.text)
    except NoSuchElementException as e:
        continue
    try:
        week=driver.find_element(By.XPATH,'/html/body/div[4]/main/div[2]/div[3]/div/div/div/div[2]/div[{}]/ul/li[4]/ul/li[7]/ul/li[5]/span'.format(i))
        WOB.append(week.text)
    except NoSuchElementException as e:
        continue

In [ ]:
print(len(song))
print(len(artist))
print(len(rank))
print(len(peak_rank))
print(len(WOB))

## 6. Scrape the details of Highest selling novels.
## compare
## A) Book name
## B) Author name
## C) Volumes sold
## D) Publisher
## E) Genre

In [212]:
driver = webdriver.Chrome()
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [213]:
Book=[]
Author=[]
Volumes=[]
Publisher=[]
Genre =[]

In [214]:
for i in range(1,101):
    book=driver.find_element(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[2]'.format(i))
    Book.append(book.text)
    author=driver.find_element(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[3]'.format(i))
    Author.append(author.text)
    vol=driver.find_element(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[4]'.format(i))
    Volumes.append(vol.text)
    pub=driver.find_element(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[5]'.format(i))
    Publisher.append(pub.text)
    genre=driver.find_element(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[6]'.format(i))
    Genre.append(genre.text)
driver.quit()

In [215]:
print(len(Book))
print(len(Author))
print(len(Volumes))
print(len(Publisher))
print(len(Genre))

100
100
100
100
100

In [216]:
ds6=pd.DataFrame({'Title':Book,'Author':Author,'Volumes Sold':Volumes,'Publisher':Publisher,'Genre':Genre})
ds6

,Title,Author,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

## 7. Scrape the details most watched tv series of all time from imdb.com.
## Url = https://www.imdb.com/list/ls095964455/ You
## have to find the following details:
## A) Name
## B) Year span
## C) Genre
## D) Run time
## E) Ratings
## F) Votes

In [217]:
driver = webdriver.Chrome()
driver.get('http://www.imdb.com/list/ls095964455/')

In [218]:
Title=[]
Yr_span=[]
Genre=[]
Time=[]
Ratings=[]
Votes=[]

In [219]:
for i in range(1,101):
    title=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[2]/div/div[1]/div/div[3]/div[3]/div[{}]/div[2]/h3/a'.format(i))
    Title.append(title.text)
    yr=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[2]/div/div[1]/div/div[3]/div[3]/div[{}]/div[2]/h3/span[2]'.format(i))
    Yr_span.append(yr.text)
    genre=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[2]/div/div[1]/div/div[3]/div[3]/div[{}]/div[2]/p[1]/span[5]'.format(i))
    Genre.append(genre.text)
    time=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[2]/div/div[1]/div/div[3]/div[3]/div[{}]/div[2]/p[1]/span[3]'.format(i))
    Time.append(time.text)
    rate=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[2]/div/div[1]/div/div[3]/div[3]/div[{}]/div[2]/div[1]/div[1]/span[2]'.format(i))
    Ratings.append(rate.text)
    vote=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[2]/div/div[1]/div/div[3]/div[3]/div[{}]/div[2]/p[4]/span[2]'.format(i))
    Votes.append(vote.text)

In [220]:
print(len(Title))
print(len(Yr_span))
print(len(Genre))
print(len(Time))
print(len(Ratings))
print(len(Votes))

100
100
100
100
100
100

In [221]:
ds7=pd.DataFrame({'Name':Title,'Yr_Span':Yr_span,'Genre':Genre,'Time Duration':Time,'Ratings':Ratings,'Votes':Votes})
ds7

,Name,Yr_Span,Genre,Time Duration,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,205,136"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",51 min,8.7,"1,276,481"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,046,273"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"307,507"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"266,583"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.5,"52,751"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"64,811"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"211,112"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"43,924"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"266,200"

In [222]:
driver.quit()

## 8. Details of Datasets from UCI machine learning repositories.
## Url = https://archive.ics.uci.edu/
## You have to find the following details:
## A) Dataset name
## B) Data type
## C) Task
## D) Attribute type
## E) No of instances
## F) No of attribute 
## G) Year

In [225]:
driver = webdriver.Chrome()
driver.get('https://archive.ics.uci.edu/')

In [226]:
try:
    view=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]')
    driver.execute_script("arguments[0].click();", view)
except NoSuchElementException as e:
    view=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]')
    driver.execute_script("arguments[0].click();", view)

In [227]:
try:
    expand=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[1]/div/label[2]')
    driver.execute_script("arguments[0].click();", expand)
except NoSuchElementException as e:
    expand=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[1]/div/label[2]')
    driver.execute_script("arguments[0].click();", expand)

In [228]:
Name=[]
Data_type=[]
Task=[]
Att_type=[]
Instances=[]
Attribute=[]
Year=[]

In [229]:
import time

In [230]:
page=int(1)
while page<66: 
        for j in range(0,2):
            expand=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[1]/div/label[2]')
            driver.execute_script("arguments[0].click();", expand)
        title=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
        for i in title:
            Name.append(i.text)
        for k in range(1,20,2):
            typed=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div[{}]/div[2]/div/table/tbody/tr/td[1]'.format(k))
            Data_type.append(typed.text)
        des=driver.find_elements(By.XPATH,'//p[@class="truncate"]')
        for i in des:
            Task.append(i.text)
        for k in range(1,20,2):
            att_type=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div[{}]/div[2]/div/table/tbody/tr/td[2]'.format(k))
            Att_type.append(att_type.text)
        for k in range(1,20,2):
            inst=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div[{}]/div[1]/div[2]/div/div[3]/span'.format(k))
            Instances.append(inst.text)
        for k in range(1,20,2):
            att=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div[{}]/div/div[2]/div/div[4]/span'.format(k))
            Attribute.append(att.text)
        for k in range(1,20,2):
            yr=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div[{}]/div[2]/div/table/tbody/tr/td[3]'.format(k))
            Year.append(yr.text)
        nextp=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[3]/div/button[2]')
        driver.execute_script("arguments[0].click();", nextp)
        time.sleep(3)
        page+=1

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div[1]/div[2]/div/table/tbody/tr/td[1]"}
  (Session info: chrome=109.0.5414.149); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
Backtrace:
	(No symbol) [0x00F26643]
	(No symbol) [0x00EBBE21]
	(No symbol) [0x00DBDA9D]
	(No symbol) [0x00DF1342]
	(No symbol) [0x00DF147B]
	(No symbol) [0x00E28DC2]
	(No symbol) [0x00E0FDC4]
	(No symbol) [0x00E26B09]
	(No symbol) [0x00E0FB76]
	(No symbol) [0x00DE49C1]
	(No symbol) [0x00DE5E5D]
	GetHandleVerifier [0x0119A142+2497106]
	GetHandleVerifier [0x011C85D3+2686691]
	GetHandleVerifier [0x011CBB9C+2700460]
	GetHandleVerifier [0x00FD3B10+635936]
	(No symbol) [0x00EC4A1F]
	(No symbol) [0x00ECA418]
	(No symbol) [0x00ECA505]
	(No symbol) [0x00ED508B]
	BaseThreadInitThunk [0x76AF6A24+36]
	RtlInitializeExceptionChain [0x778DA9FF+143]
	RtlInitializeExceptionChain [0x778DA9CA+90]

In [138]:
print(len(Name))
print(len(Data_type))
print(len(Task))
print(len(Att_type))
print(len(Instances))
print(len(Attribute))
print(len(Year))

650
650
650
650
650
650
650

In [139]:
ds8=pd.DataFrame({'Dataset Name':Name,'Data Type':Data_type,'Task':Task,'Attribute type':Att_type,'No Of Instances':Instances,'No Of Attributes':Attribute,'Year':Year})
ds8

,Dataset Name,Data Type,Task,Attribute type,No Of Instances,No Of Attributes,Year
0,Iris,Life Science,"A small classic dataset from Fisher, 1936. One...",Real,150 Instances,4 Features,7/1/1988
1,Heart Disease,Life Science,"4 databases: Cleveland, Hungary, Switzerland, ...","Categorical, Integer, Real",303 Instances,13 Features,7/1/1988
2,Adult,Social Science,Predict whether income exceeds $50K/yr based o...,"Categorical, Integer",48.84K Instances,14 Features,5/1/1996
3,Dry Bean Dataset,Computer Science,"Images of 13,611 grains of 7 different registe...","Integer, Real",13.61K Instances,16 Features,9/14/2020
4,Diabetes,Life Science,This diabetes dataset is from AIM '94,"Categorical, Integer",,20 Features,N/A
...,...,...,...,...,...,...,...
645,Pedal Me Bicycle Deliveries,Social Science,A dataset of weekly bicycle package deliveries...,Real,36 Instances,15 Features,8/14/2023
646,Average Localization Error (ALE) in sensor nod...,Computer Science,This data set can be used to test any regressi...,Real,107 Instances,6 Features,8/14/2023
647,Visegrad Group companies data,Business,The dataset concerns listed companies of the V...,Real,85 Instances,450 Features,7/17/2023
648,TamilSentiMix,Computer Science,We created a gold standard Tamil-English code-...,Categorical,15.74K Instances,,8/14/2023
649,SUPPORT2,Life Science,This dataset comprises 9105 individual critica...,"Real, Categorical, Integer",9.11K Instances,40 Features,9/15/2023

In [140]:
driver.quit()